# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nopassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 215)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txbPass1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txbPass1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txbPass1.setObjectName("txbPass1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txbPass1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txbPass2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txbPass2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txbPass2.setObjectName("txbPass2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txbPass2)
        self.btnLoginNP = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoginNP.setObjectName("btnLoginNP")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.btnLoginNP)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName("btnCancel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btnCancel)
        self.txbUser = QtWidgets.QLabel(self.centralwidget)
        self.txbUser.setObjectName("txbUser")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txbUser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">You don\'t have a password, create new password</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Username:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Password:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Confirm password:</span></p></body></html>"))
        self.btnLoginNP.setText(_translate("MainWindow", "Login"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))
        self.txbUser.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">TextLabel</span></p></body></html>"))
