# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(294, 136)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 591, 441))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 272, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txbPass = QtWidgets.QLineEdit(self.layoutWidget)
        self.txbPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txbPass.setObjectName("txbPass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txbPass)
        self.btnLoginP = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLoginP.setObjectName("btnLoginP")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.btnLoginP)
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnCancel)
        self.txbUser = QtWidgets.QLabel(self.layoutWidget)
        self.txbUser.setObjectName("txbUser")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txbUser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Username:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Password:</span></p></body></html>"))
        self.btnLoginP.setText(_translate("MainWindow", "Login"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))
        self.txbUser.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">TextLabel</span></p></body></html>"))
